Algoritmo Desencolar
	Leer arreglo_con_datos
	Leer La_primera_posicion_del_arreglo_en_la_posicion_0
	Guardar_el_primer_valor_del_arrelgo_en_una_variable
	Asignar_valor_""_en_la_primera_posicion_del_arreglo
	Imprimir La-varible_con_el_primer_valor_del_arreglo
	Imprimir El_arreglo_sin_el_primer_valor
FinAlgoritmo
